### ISSUE TITLE
Connect ETHVM to Private PoA Chain

### ISSUE THREAD

**Issue by teslashibe** [enKryptIO/ethvm#103]
* **I'm submitting a ...**
    - [x] feature request
    
I am building a custom proof-of-authority testnet and am looking for a way to use ETHVM on a private testnet or network. 

Is this easily implemented with config changes and are there any available guides for this?

**Comment by aldoborrero** [comment]
Hi @teslashibe 

For now we're using EthereumJ as  source of truth for provisioning blockchain data. Currently EthereumJ does not support properly PoA as they have stated on their issue tracker (https://github.com/ethereum/ethereumj/issues/1102).

Altough, I don't believe is too hard to make the code to support it (but this means that you have to modify properly EthereumJ to work).

We're currently finishing our first iteration for EthVM to work properly with PoW networks and something that we're going to work sooner than later is to properly support Parity client as a an alternative source of input, so this will give us direct access to any PoA. The only caveat is t hat I can't give you an estimate of time properly on when will happen.

**Comment by aldoborrero** [comment]
Hi @teslashibe after coming from devcon I can tell you that we're going to migrate directly to Pantheon (the new enterprise ready ethereum client which by default supports PoA).

So good news!

**Comment by aldoborrero** [comment]
I'm closing this issue as we're going to tackle it soon!
