### ISSUE TITLE
Private Chain

### ISSUE THREAD

**Issue by CryptoMountains** [enKryptIO/ethvm#127]
Hi! i'm building a private ethereum chain using puppeth and Proof of Authority. I would like to use this great explorer! how can I connect my chain to this explorer and install it? 
Wiki is not working.
Thank you very much

**Comment by niktrix** [comment]
Hi @CryptoMountains 

As of now EthVM uses ethereumj to to get explorer data, ethereumj as of now don't support POA network, In our roadmap we are going to add support for Pantheon Ethereum client, which supports POA.
Once migration to Pantheon Ethereum client is finish you can use EthVM explorer for your private network.
