### ISSUE TITLE
Research why sometimes front-end behaves slow

### ISSUE THREAD

**Issue by aldoborrero** [enKryptIO/ethvm#128]
This task should take care of researching why the front-end is behaving sometimes slow.

**Comment by niktrix** [comment]
Time difference between page load and  first api call is approx 2 sec

**Comment by aldoborrero** [comment]
@olgakup ping

**Comment by niktrix** [comment]
First websocketis called on created hook of vue

**Comment by aldoborrero** [comment]
@niktrix did you find any evidence that this apparent slowness was being caused by our server? Or any api calls?
