### ISSUE TITLE
Rethink DB is discontinued

### ISSUE THREAD

**Issue by nickjuntilla** [enKryptIO/ethvm#13]
* **I'm submitting a ...**
    - [x] bug report

* **Bug Report**

Rethink DB is discontinued and won't install on Ubuntu 18.4 LTS. Perhaps an alternative DB can be used.

**Comment by niktrix** [comment]
you can always use docker to run rethinkdb, using alternative DB is in consideration

**Comment by aldoborrero** [comment]
We're planning to move away from Rethink but will be in a future release, first we need other things solved before committing time to do the transition.

As niktrix pointed out, using Docker, will allow to use Rethink easily. So I'm closing this issue (as is more an enhancement).

Thanks!
