### ISSUE TITLE
Move all monkey dependencies to bin

### ISSUE THREAD

**Issue by aldoborrero** [enKryptIO/ethvm#131]
Currently we have:

- package.json
- yarn.lock
- tsconfig.json
- tslint.json
- prettierrc

Sitting at the top of ethvm repository, but those dependencies are strictly related to monkey utility script.

This task should take care of moving those files to bin/monkey. This will avoid confusion for newcomers.

Make sure also that greenkeeper is updated with the new path.

**Comment by niktrix** [comment]
Done
