### ISSUE TITLE
Relative path don't work in docker-compose

### ISSUE THREAD

**Issue by kurthalex** [enKryptIO/ethvm#161]
**Bug Report**

Following the getting started wiki, after executing `docker-compose up -d`, I got 2 errors. 

* Docker network

*ERROR: Network web declared as external, but could not be found. Please create the network manually using `docker network create web` and try again.*

It works executing `docker network create web` maybe it could be added in the doc 

* Path inside docker-compose

*ERROR: Cannot locate specified Dockerfile: ./apps/ethvm/Dockerfile.dev*

Relative path don't seem to work. So I replaced all `./` by `/home/my_user/path_of_ethvm_repo` inside docker-compose.yaml and docker-compose.extra.yaml and now it works

I tried both on Ubuntu and Archlinux

**Comment by niktrix** [comment]
@kurthalex Thanks for pointing out this, we  will update the network creating command in documentation.

you can use dev build script to start EthVM with data 

````
cd ethvm
./bin/up-simple.sh
````

**Comment by kurthalex** [comment]
Thank you !
In order to execute the dev build script, git-lfs has to be added in prerequisites (got an error because it wasn't on my system)

Still an error while executing ./bin/up-simple.sh

    Executing: mongorestore -- archive="./datasets/ethvm_mainnet_sample.mongo.archive"
    2018-11-21T16:37:32.172+0000	Failed: stream or file does not appear to be a mongodump archive*
