### ISSUE TITLE
Mongorestore fails while executing up-simple.sh

### ISSUE THREAD

**Issue by kurthalex** [enKryptIO/ethvm#163]
* **Bug Report**

I'm following the wiki to try ethvm 

While executing `./bin/up-simple.sh`, I got this error

    Executing: mongorestore --archive="/datasets/ethvm_mainnet_sample.mongo.archive"
    2018-11-22T23:30:19.752+0000    Failed: stream or file does not appear to be a mongodump archive

Plus, git-lfs has to be added to prerequisites because another error is raised before this step if the package is not installed on the system

Tried on ubuntu 18.04 and archlinux

**Comment by niktrix** [comment]
run 
git lfs checkout 
before exucuting up-simple.sh

**Comment by kurthalex** [comment]
It worked, thank you
