### ISSUE TITLE
Docker-compose can not work well 

### ISSUE THREAD

**Issue by hashfury42** [enKryptIO/ethvm#19]
Hi, when I start this project by docker-compose cmd on my Mac, this happened:

```
docker-compose up -d
Creating network "ethvmdevkitmaster_back" with driver "bridge"
ERROR: Pool overlaps with other one on this address space
```
By the way, ethvm seems to be a GREAT project, but can you give us more details on how to install it and deploy it?

**Comment by aldoborrero** [comment]
hi @hashfury42 would you mind to test this [proposed solution](https://github.com/maxking/docker-mailman/issues/85)? It's docker related

**Comment by aldoborrero** [comment]
Great news @hashfury42 !!! :)

I'm going to close this issue then, if you have other issues, please open new ones.

Thanks
