### ISSUE TITLE
Add to UncleRecord

### ISSUE THREAD

**Issue by aldoborrero** [enKryptIO/ethvm#238]
- BlockHeight: Real block number where it appeared
- Position / Index (or another name): The position where the uncle was in the array
- Uncle reward (just reward for the uncle)

Take a look on: https://etherscan.io/uncles

**Comment by brianmcgee** [comment]
@aldoborrero I have reviewed the code and from what I see the number field within the uncle should be  `a scalar value equal to the number of ancestor blocks.` I believe this is what we require. 

The position/index I can add easily however the uncle reward could be more problematic. 

We receive a map of `address -> reward`. We can correlate these with the `author` field of the uncle headers however what about the case where a miner address appears multiple times within the uncles list for different blocks? This should be a highly unlikely / impossible scenario correct?
