### ISSUE TITLE
Add total number of txs an address has been involved

### ISSUE THREAD

**Issue by aldoborrero** [enKryptIO/ethvm#260]
Currently we have the following in the front-end:

![photo_2019-01-22_22-00-11](https://user-images.githubusercontent.com/82811/51604495-4427b680-1f0d-11e9-9e7d-4758bd8aaed3.jpg)

If you take notice we are requesting information of total txs an address / contract has been involved.

The current query on the backend is:

```
public getAddressTotalTxs(hash: string): Promise<number> {
    return this.db
      .collection(MongoEthVM.collections.transactions)
      .countDocuments({ $or: [{ from: hash }, { to: hash }] })
      .then(resp => {
        if (!resp) {
          return 0
        }
        return resp
      })
}
```

Basically we're counting the total number which is not optimal if the address / contract has lot of them.

So maybe we can create a collection called address_metadata, and inside them we can add information like:

- Total Txs: that the address has been involved (this includes in and from)
- Total In Txs: Only Txs that are referred to this address
- Total Out Txs: Only txs that are from this address
- IsMiner: If the address has been involved and have been rewarded while mining (this is already done but as above, the queries are searching for a block that has been mined. We can speed up that as well)
- IsContractCreator: If the address has created at least one contract (same as above)

We can reuse later this collection to add more stats and info as needed.

This task is comprised of:

- [x] Creating in Kafka-Processor and Kafka-Connect the collection address_metadata (and update code to make this behavior happen)
- [x] Updating calls in API to increase performance
- [x] Update front-end with mentioned API calls

**Comment by brianmcgee** [comment]
@aldoborrero processing side is completed. This task is now ready for API integration
