### ISSUE TITLE
Small issues with Charts

### ISSUE THREAD

**Issue by aldoborrero** [enKryptIO/ethvm#268]
This issue is related to some more changes we need to perform on charts (so better to document those to have a proper record).

<img width="565" alt="screen shot 2019-01-25 at 13 07 31" src="https://user-images.githubusercontent.com/82811/51746097-50467c00-20a5-11e9-9416-306d688f7fe9.png">

All the components affected are located `explorer/src/modules/charts/history/`

- Remove hardcoded strings using computed and vue-i18n
- Rename the class (for some classes it doesn't match the name of the file with the name of the class)
- The component `ChartUnclesNumber.vue` (above image) it references Events.getUnclesStats which doesn't exist. Can we double check that is correct?

Other related issues is that whenever I enter to one chart it doesn't redraw the component. So we need to double check the logic (maybe this was the thing you were mentioning @olgakup ). For now you can create a PR fixing above mentioned comments (that are easy to tackle) and we can create another one for fixing rendering issues.

**Comment by olgakup** [comment]
@aldoborrero particularly for uncles chart, I think we are not using it any more are we? unless we are posting total number of uncles per day?

**Comment by olgakup** [comment]
@aldoborrero hey can you clarify if develop was merged with the charts branch? I think the merge messed up a little, i see some stuff that I changed yesterday

**Comment by olgakup** [comment]
HeyI fixed hard coded string and class names, as well as chart axis format. @brianmcgee I know you will implement number of uncles event soon, but unfortunately I could not find average number of pending transactions history event, not sure if it is implemented.  Can you point me where it is?
