### ISSUE TITLE
"Forbidden path outside the build context" when running "docker-compose up -d"

### ISSUE THREAD

**Issue by eumend** [enKryptIO/ethvm#54]
* **I'm submitting a ...**
    - [x] bug report

* **Feature Request**
I'm following the installation README. When I run:
`docker-compose up -d`
I get:
```
Building geth_miner
ERROR: Forbidden path outside the build context: ../../provisioners/docker/images/dev/eth/Dockerfile ()
```
And compose stops cold. While I think I could get around this playing with the Dockerfile, is there any reason I'm getting this error message?

* **Bug Report**
    - What is the current behavior?
`docker-compose up -d` isn't working for me, fails with above error message
    - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Follow the readme up to the [Developing](https://github.com/enKryptIO/ethvm#developing) step.
    - What is the expected behavior?
Docker compose builds the images correctly
        - Operating system
Ubuntu 16.04

**Comment by eumend** [comment]
@aldoborrero no dice, I did use the --recursive flag and I also tried with the submodule commans, still gives me the same error.

**Comment by aldoborrero** [comment]
Wow, it surprises me because it only showcases error for geth_miner, but does geth service gets build properly?

**Comment by eumend** [comment]
@aldoborrero This was an error on my part. I forgot the very important detail that I changed the compose version in the compose yaml file after getting a compose version warning. I did this because I thought I had the latest version already, but I didn't. I've already installed compose 1.22 and it builds fine. Sorry!

**Comment by aldoborrero** [comment]
@eumend glad to hear it! 👍
