### ISSUE TITLE
Frontend Blockchain UI empty?

### ISSUE THREAD

**Issue by eumend** [enKryptIO/ethvm#64]
I'm not sure if this is a bug or I'm doing something wrong, but when I enter to ethvm.lan the UI displays correctly, however, all blockchain information is empty, eg: "Last block" just displays empty brackets, hash rate and difficulty show 0, there are no blocks in the feed etc.

Thing is, I checked the logs and the server at leasts seems to be emitting and storing blocks fine. From the "ethvm" logs, the only errors I get are some from "ethvm/src/libs/Block.ts".

Is this normal? And, is this supposed to connect to the mainnet, a testnet, a freshly created blockchain? And if it's the latter, how can I make it connect to say, the mainnet? Thanks!

**Comment by niktrix** [comment]
Can you check if your geth container is running, this setup does not  connects to mainnet.

**Comment by aldoborrero** [comment]
@eumend also, can you check that inside apps/eth is on master? It looks like that you're on a previous commit (remember that inside that folder there's a git submodule).

And for now, for exploring mainnet, you need to index it by yourself running geth in production mode (i.e updating geth inside docker-compose and removing geth_miner). I don't recommend it to do it as you need to sync with main ethereum net, which is going to take weeks!
