### ISSUE TITLE
How to save data on external hard drive on Azure

### ISSUE THREAD

**Issue by KushalKochar** [enKryptIO/ethvm#69]
Hi,

I am in need of indexer (eth) for 1 of my project, and exploring the use of ETHVM.

Can anyone please provide some information about how to configure the project:

Where can I configure to save all the data (Ethereum blockchain, indexed data etc.) on external hard drive on Azure linux VM.

Any other configuration settings which I should be changing for production environment?

**Comment by aldoborrero** [comment]
Hi @KushalKochar, currently EthVM is being actively developed, so there's no support yet to be deployed officially to any cloud provider (that includes AWS).

Said that, there's a folder called provisioners and inside another one called k8s. In there you will find an initial set of files that adjusted produces a cluster (but is not finished and you need tweaking it). We're not going to work on that part til we have a stable version produced.

Another option is to use docker-compose and try to create a Docker Swarm cluster. If that's the case, then I recommend you to visit those websites to learn more, as this is more a question than a issue.
