### ISSUE TITLE
No enkryptio/ethvm-socket-server:latest founded

### ISSUE THREAD

**Issue by bradyjoestar** [enKryptIO/ethvm#8]
* **I'm submitting a ...**
    
    - [ ] bug report

* **Bug Report**
   I'm using docker-compose.yml to start up the project,but when pulling the enkryptio/ethvm-socket-server:latest it told me failed.
  How can I found the image?Thanks for your help!

**Comment by aldoborrero** [comment]
Hi @bradyjoestar for now, we're working on a refactor on ethvm-socket-server (so you have to build the image yourself).

Keep in mind that image will not properly work as expected (until the refactor is finished and tested). That's the reason why the image is not uploaded to Docker Hub.

So, I recommend you to comment that section of the compose file (the front end will still work with mocked data) or download ethvm-socket-server (branch master and do the manual setup).

**Comment by aldoborrero** [comment]
Full rewrite has been done, you can take a look on ethvm-dev-kit (if you want to have a locally environment with the server and client).

Also, we're working on mixing all those three repositories (this one, ethvm-socket-server and ethvm-dev-kit into one. The structure will follow ethvm-dev-kit).

So, expect more changes soon also. (I'll ping you again on this issue to notify you).

**Comment by bradyjoestar** [comment]
@aldoborrero  Thanks for your notification!I will try it right now!
Thanks for yout great contributions!
